spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate