server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:liftbookdb
    username: user
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  h2:
    console:
      enabled: true