name: LiftBook API Continuous Delivery

on:
  push:
    branches: [master]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Workaround No such reference 'origin/main'
      # https://github.com/diffplug/spotless/issues/710

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Code Formatting Spotless Check
        run: mvn spotless:check

      - name: Code compilation
        run: mvn compile

      - name: Unit testing
        run: mvn test

      # https://github.com/marketplace/actions/render-deploy-action

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}